const q=s=>document.querySelector(s);document.querySelectorAll("#chips button").forEach(b=>b.onclick=()=>b.classList.toggle("active"));

function profile(x){x=x.toLowerCase();if(/japan|tokyo|kyoto/.test(x))return["Japan",1.3,1.2,.9,.7,.55];if(/kina|kinamuren|beijing|peking/.test(x))return["Kina",1.35,1.1,.9,.4,.5];if(/florida|orlando|miami/.test(x))return["Florida",.8,1.1,1.3,1.35,.35];if(/frankfurt|berlin|paris|london|münchen|munich/.test(x))return[x,1.25,.8,1,.35,1.25];if(/italien|rom|venedig|milano|sicilien/.test(x))return["Italien",1.15,1.05,1.05,.65,.8];if(/spanien|barcelona|madrid|mallorca|teneriffa|kanarie/.test(x))return["Spanien",.95,1.1,1.25,.85,.9];if(/grekland|aten|kreta|rhodos|kos/.test(x))return["Grekland",.9,1.05,1.35,.8,.85];if(/thailand|bangkok|phuket/.test(x))return["Thailand",1.15,1.1,1.35,.7,.45];return[x||"Valfri destination",1,1,1,.8,.8]}

function days(){let a=q("#from").value,b=q("#to").value;if(!a||!b)return 7;return Math.max(1,Math.round((new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/86400000))}

function priorities(){return[...document.querySelectorAll("#chips .active")].map(x=>x.dataset.v)}
function ptext(p){let m={sol:"sol & bad",familj:"familj",budget:"budget",kultur:"kultur",natur:"natur",kort:"kort restid"};return p.length?p.map(x=>m[x]||x).join(", "):"en balanserad resa"}

function reason(p){let n=p[0];if(/Japan/i.test(n))return"mycket starkt för kultur, upplevelser och variation, men den långa resan gör budget och reslängd extra viktiga.";if(/Kina/i.test(n))return"starkt för kultur och stora upplevelser. Den längre resvägen gör en längre vistelse mer motiverad.";if(/Florida/i.test(n))return"starkt för sol, bad och familjeupplevelser. Aktiviteter och transporter kan snabbt påverka budgeten.";if(/Frankfurt|Berlin|Paris|London|München|Munich/i.test(n))return"bra för kultur, mat och upplevelser med relativt kort restid inom Europa.";if(/Italien/i.test(n))return"bra balans mellan kultur, mat, upplevelser och avkoppling.";if(/Spanien/i.test(n))return"flexibelt för både sol, bad, kultur och familjeresor.";if(/Grekland/i.test(n))return"särskilt starkt när sol, bad och avkoppling väger tungt.";if(/Thailand/i.test(n))return"starkt för värme, bad, mat och upplevelser, men den långa resan gör längre vistelser mer attraktiva.";return"kan anpassas efter era prioriteringar. I en senare version kan riktiga pris- och reseuppgifter hämtas automatiskt."}

function score(p,pri,ds,b){let s=72;if(pri.includes("familj"))s+=p[3]*5;if(pri.includes("kultur"))s+=p[1]*5;if(pri.includes("natur"))s+=p[2]*4;if(pri.includes("sol"))s+=p[4]*5;if(pri.includes("budget"))s+=(1.2-p[1])*4;if(pri.includes("kort"))s+=p[5]*4;if(ds>=10&&p[0]!=="Frankfurt")s+=2;if(ds<=5&&p[5]>1)s+=3;if(b<8000&&p[0]==="Thailand")s-=4;return Math.min(97,Math.max(55,Math.round(s)))}

q("#go").onclick=()=>{let d=q("#destination").value.trim()||"Valfri destination",p=profile(d),n=Math.max(1,+q("#people").value||1),b=Math.max(0,+q("#budget").value||10000),ds=days(),pri=priorities(),known=["Grekland","Spanien","Italien","Frankfurt"].map(profile),c=[p,...known.filter(x=>x[0].toLowerCase()!=p[0].toLowerCase())].map(x=>({p:x,s:score(x,pri,ds,b)})).sort((a,b)=>b.s-a.s),w=c[0],pp=Math.round(b/n);

let html=`<div class="thinking"><h2>🧠 ResAgent v1.0</h2><p><b>Min första bedömning:</b> Jag väger ihop ${n} resenärer, ${ds} dagar, ${b.toLocaleString("sv-SE")} kr och era prioriteringar – ${ptext(pri)}.</p><p><b>Budget:</b> ${b.toLocaleString("sv-SE")} kr totalt (${pp.toLocaleString("sv-SE")} kr/person).</p><p><b>Min starkaste kandidat:</b> ${w.p[0]} – ${w.s}/100. ${reason(w.p)}</p><p>Jag försöker hitta bästa helheten snarare än att automatiskt välja det billigaste alternativet.</p></div><article class="option"><span class="badge">🏆 MIN REKOMMENDATION · ${w.s}/100</span><h2>${w.p[0]}</h2><p class="muted">Inte bara billigast – bäst total matchning mot era önskemål.</p><div class="ranking">${c.slice(0,4).map((x,i)=>`<div class="rank"><b>${i+1}. ${x.p[0]}</b>Matchning: ${x.s}/100</div>`).join("")}</div><p class="reason"><b>🎯 Vad vinner ni?</b> ${reason(w.p)}</p></article>`;

[["🥇 SMART BUDGET",.86,"Maximerar värdet inom budgeten."],["🥈 BÄST BALANS",1,"Balanserar upplevelser, vila och kostnad."],["🥉 MEST UPPLEVELSE",1.14,"Ger mer utrymme för upplevelser och bekvämlighet."]].forEach((x,i)=>{let total=Math.round(b*x[1]/10)*10,l=Math.round(total*.34/10)*10,t=Math.round(total*.28/10)*10,f=Math.round(total*.2/10)*10,a=total-l-t-f,s=Math.min(97,Math.max(50,w.s-i*2+(pri.includes("budget")&&i===0?2:0)));html+=`<article class="option"><span class="badge">${x[0]} · ${s}/100</span><h2>${w.p[0]} – ${i===0?"smart budget":i===1?"balanserad":"mest upplevelse"}</h2><div class="price">${total.toLocaleString("sv-SE")} kr</div><p class="muted">${x[2]}</p><div class="break"><div><b>Boende</b>${l.toLocaleString("sv-SE")} kr</div><div><b>Transport</b>${t.toLocaleString("sv-SE")} kr</div><div><b>Mat</b>${f.toLocaleString("sv-SE")} kr</div><div><b>Aktiviteter</b>${a.toLocaleString("sv-SE")} kr</div></div><p class="reason"><b>🧠 Min rekommenderade kompromiss.</b> ${i===0?"Jag skyddar budgeten och behåller de viktigaste upplevelserna.":i===1?"Jag balanserar kostnad, komfort och upplevelser.":"Här används mer av budgeten för komfort och fler upplevelser."}</p>${total<=b?'<div class="good">✓ Rymmer inom budgeten.</div>':'<div class="warn">⚠️ Över budget – detta är priset för mer komfort eller fler upplevelser.</div>'}</article>`});q("#out").innerHTML=html;q("#out").scrollIntoView({behavior:"smooth"})}